"""Baseline schema. Generated from arb.db metadata, not hand-written.

Part B.4 of the build plan is the contract; deviations are recorded in SPEC.md

Revision ID: 3af032b29528
Revises:
Create Date: 2026-08-19 16:18:34.085257

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import arb.db

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comps_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_hash", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("payload", sa.String(), nullable=False),
        sa.Column("fetched_at", arb.db.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comps_cache", schema=None) as batch_op:
        batch_op.create_index("idx_comps", ["query_hash", "fetched_at"], unique=False)

    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("venue", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("price_pence", sa.Integer(), nullable=False),
        sa.Column("total_pence", sa.Integer(), nullable=True),
        sa.Column("brand_norm", sa.String(), nullable=True),
        sa.Column("title_norm", sa.String(), nullable=True),
        sa.Column("size_norm", sa.String(), nullable=True),
        sa.Column("colour_norm", sa.String(), nullable=True),
        sa.Column("condition_band", sa.String(), nullable=True),
        sa.Column("category_id", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("seller_id", sa.String(), nullable=True),
        sa.Column("favourites", sa.Integer(), nullable=True),
        sa.Column("views", sa.Integer(), nullable=True),
        sa.Column("first_seen", arb.db.UtcDateTime(), nullable=False),
        sa.Column("last_seen", arb.db.UtcDateTime(), nullable=False),
        sa.Column("disappeared_at", arb.db.UtcDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue", "external_id", name="uq_listings_venue_external"),
    )
    op.create_table(
        "vinted_ref",
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("title_norm", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("item_count", sa.Integer(), nullable=True),
        sa.Column("loaded_at", arb.db.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("kind", "external_id"),
    )
    with op.batch_alter_table("vinted_ref", schema=None) as batch_op:
        batch_op.create_index("idx_vinted_ref_norm", ["kind", "title_norm"], unique=False)

    op.create_table(
        "opportunities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=True),
        sa.Column("est_p25_pence", sa.Integer(), nullable=False),
        sa.Column("est_p60_pence", sa.Integer(), nullable=False),
        sa.Column("comp_n", sa.Integer(), nullable=False),
        sa.Column("est_confidence", sa.Float(), nullable=False),
        sa.Column("match_confidence", sa.Float(), nullable=False),
        sa.Column("fees_pence", sa.Integer(), nullable=False),
        sa.Column("ship_in_pence", sa.Integer(), nullable=False),
        sa.Column("ship_out_pence", sa.Integer(), nullable=False),
        sa.Column("net_pence", sa.Integer(), nullable=False),
        sa.Column("roi", sa.Float(), nullable=False),
        sa.Column("days_to_sell_p50", sa.Float(), nullable=True),
        sa.Column("capital_velocity", sa.Float(), nullable=True),
        sa.Column("qty", sa.Integer(), server_default="1", nullable=False),
        sa.Column("fee_table_version", sa.String(), nullable=False),
        sa.Column("scored_at", arb.db.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("opportunities", schema=None) as batch_op:
        batch_op.create_index("idx_rank", ["capital_velocity", "scored_at"], unique=False)

    op.create_table(
        "sold_obs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand_norm", sa.String(), nullable=True),
        sa.Column("title_norm", sa.String(), nullable=True),
        sa.Column("size_norm", sa.String(), nullable=True),
        sa.Column("colour_norm", sa.String(), nullable=True),
        sa.Column("condition_band", sa.String(), nullable=True),
        sa.Column("category_id", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("price_pence", sa.Integer(), nullable=False),
        sa.Column("ship_pence", sa.Integer(), nullable=True),
        sa.Column("listed_at", arb.db.UtcDateTime(), nullable=True),
        sa.Column("sold_at", arb.db.UtcDateTime(), nullable=True),
        sa.Column("days_to_sell", sa.Integer(), nullable=True),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_row"],
            ["comps_cache.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sold_obs", schema=None) as batch_op:
        batch_op.create_index(
            "idx_block", ["brand_norm", "size_norm", "condition_band"], unique=False
        )

    op.create_table(
        "decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=True),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("skip_reason", sa.String(), nullable=True),
        sa.Column("decided_at", arb.db.UtcDateTime(), nullable=False),
        sa.Column("spend_pence", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("decision_id", sa.Integer(), nullable=True),
        sa.Column("cost_pence", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), server_default="1", nullable=False),
        sa.Column("acquired_at", arb.db.UtcDateTime(), nullable=False),
        sa.Column("listed_at", arb.db.UtcDateTime(), nullable=True),
        sa.Column("sold_at", arb.db.UtcDateTime(), nullable=True),
        sa.Column("gross_pence", sa.Integer(), nullable=True),
        sa.Column("actual_fees_pence", sa.Integer(), nullable=True),
        sa.Column("actual_ship_pence", sa.Integer(), nullable=True),
        sa.Column("realised_net_pence", sa.Integer(), nullable=True),
        sa.Column("sa103_category", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inventory")
    op.drop_table("decisions")
    with op.batch_alter_table("sold_obs", schema=None) as batch_op:
        batch_op.drop_index("idx_block")

    op.drop_table("sold_obs")
    with op.batch_alter_table("opportunities", schema=None) as batch_op:
        batch_op.drop_index("idx_rank")

    op.drop_table("opportunities")
    with op.batch_alter_table("vinted_ref", schema=None) as batch_op:
        batch_op.drop_index("idx_vinted_ref_norm")

    op.drop_table("vinted_ref")
    op.drop_table("listings")
    with op.batch_alter_table("comps_cache", schema=None) as batch_op:
        batch_op.drop_index("idx_comps")

    op.drop_table("comps_cache")
    # ### end Alembic commands ###
