"""Add sold_obs.price_is_upper_bound.

Forced by the SoldComps contract: bestOfferAccepted=true means soldPrice is the
listed price, not the realised one. Without this flag every valuation drawn from a
Best Offer sale is biased upward and nothing downstream can tell

Revision ID: ce8c2fa2c84f
Revises: 0001_baseline
Create Date: 2026-08-20 08:52:46.221563

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_upper_bound"
down_revision: str | Sequence[str] | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sold_obs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("price_is_upper_bound", sa.Boolean(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sold_obs", schema=None) as batch_op:
        batch_op.drop_column("price_is_upper_bound")

    # ### end Alembic commands ###
